services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    networks:
      - app-network

  vite:
    image: node:22
    working_dir: /var/www/resources/js
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
